services:
#mandatory
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    env_file: ".env"
    secrets:
      - db_pwd
      - wp_user_pwd
      - wp_admin_pwd

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    volumes:
      - wp:/var/www/wordpress
      - hugo:/var/www/hugo
    networks:
      - inception
    env_file: ".env"
    ports:
      - "443:443"
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception
    env_file: ".env"
    secrets:
      - db_pwd
      - wp_user_pwd
      - wp_admin_pwd
    depends_on:
      - mariadb

#bonus
  redis:
      build: ./requirements/bonus/redis 
      image: redis
      container_name: redis
      networks:
        - inception
      ports:
        - '6379:6379'
      restart: always
      expose:
        - '6379'

  ftp:
      build: ./requirements/bonus/ftp
      image: ftp
      container_name: ftp
      networks:
        - inception
      ports:
        - '21:21'
        - '20:20'
      restart: always
      volumes:
        - wp:/srv/ftp

  adminer:
      build: ./requirements/bonus/adminer
      image: adminer
      container_name: adminer
      networks:
        - inception
      ports:
        - '8080:8080'
      restart: always
      depends_on:
        - mariadb

networks:
  inception:
    name: inception

secrets:
  db_pwd:
    file: ../secrets/db_pwd.txt
  wp_user_pwd:
    file: ../secrets/wp_user_pwd.txt
  wp_admin_pwd:
    file: ../secrets/wp_admin_pwd.txt

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      device: /home/lpaquatt/data/db
      o : bind
      type : none
  wp:
    name: wp
    driver: local
    driver_opts:
      device: /home/lpaquatt/data/wp
      o : bind
      type : none
  hugo:
    name: hugo
    driver: local
    driver_opts:
      device: /home/lpaquatt/data/hugo
      o : bind
      type : none
