FROM			debian:bullseye
RUN				apt-get update -y
RUN				apt-get upgrade -y
RUN				apt-get install -y mariadb-server
COPY			./init_mariadb.sh /home/init_mariadb.sh
RUN				chmod 777 /home/init_mariadb.sh
ENTRYPOINT		[ "/home/init_mariadb.sh" ]
