FROM			debian:bullseye
RUN				apt update -y
RUN				apt upgrade -y
RUN				apt install -y mariadb-server
COPY			./init_mariadb.sh /home/init_mariadb.sh
RUN				chmod 777 /home/init_mariadb.sh
ENTRYPOINT		[ "/home/init_mariadb.sh" ]
