FROM	debian:bullseye
RUN		apt-get update -y
RUN		apt-get upgrade -y
RUN		apt-get install git -y 

#installing go
RUN		apt-get install curl -y
RUN		curl -o /usr/local/go1.12.7.linux-amd64.tar.gz https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz && \
		tar -xvf /usr/local/go1.12.7.linux-amd64.tar.gz -C /usr/local && \
		rm /usr/local/go1.12.7.linux-amd64.tar.gz
ENV 	GOPATH=/root/work
ENV 	PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
COPY 	./hugo /usr/local/bin
RUN		chmod +x /usr/local/bin/hugo

COPY	./site /var/site


COPY	./entrypoint.sh /home/entrypoint.sh
RUN		chmod +x /home/entrypoint.sh
ENTRYPOINT [ "/home/entrypoint.sh" ]

# CMD		["hugo server", "-D", "--bind 0.0.0.0"]
# CMD 	["tail", "-f", "/dev/null"]