FROM	debian:bullseye
RUN		apt update -y && apt upgrade -y \
		apt install vsftpd -y
RUN		sed -i 's/^anonymous_enable=NO/anonymous_enable=YES/' /etc/vsftpd.conf
RUN		mkdir -p /var/run/vsftpd/empty
CMD		["vsftpd", "/etc/vsftpd.conf"]
