FROM	debian:bullseye
RUN		apt-get update -y
RUN		apt-get upgrade -y
RUN		apt-get install vsftpd -y
RUN		sed -i 's/^anonymous_enable=NO/anonymous_enable=YES/' /etc/vsftpd.conf

# CMD		["vsftpd", "/etc/vsftpd.conf"]
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

# CMD 	["tail", "-f", "/dev/null"]