FROM		debian:bullseye
RUN			apt update -y
RUN			apt upgrade -y
# RUN			apt install -y php php-fpm
RUN			apt install adminer -y
# RUN			apt install -y php-mysql
# RUN			apt install -y mariadb-server mariadb-client
CMD 		["tail", "-f", "/dev/null"]