FROM			debian:bullseye
RUN				apt update -y && apt upgrade -y \
				&& apt install -y php curl php-fpm redis-server php-redis php-mysql mariadb-client
COPY			./init_wp.sh /home/init_wp.sh
RUN				chmod 777 /home/init_wp.sh
ENTRYPOINT		[ "/home/init_wp.sh" ]
# CMD 			["tail", "-f", "/dev/null"]